config-bootstrapper/src/main/resources/configs/config-bootstrapper/application.conf

- Kube adds default env for port as `ATTRIBUTE_SERVICE_PORT`, so we are adding the suffix `_CONFIG` for app-related host/port config

fixed conflicting names between app envs vs kube envs

---

config-bootstrapper/build.gradle.kts
config-bootstrapper/src/main/java/org/hypertrace/core/bootstrapper/ConfigBootstrapper.java

Currently, the bootstrap runner is used only as a command-line tool, refactoring a bit to expose to other projects. So, it can be used from `federated` service as background tasks to create attributes.
This will help in the reduction of the container in the local setup mode of HT.

exposes bootstrap runner to be used by other project

---

config-bootstrapper/build.gradle.kts

Upgrading the docstore version to latest, which changes the mongo java driver used from 3.12 to 4.1.1. This is because the previous java driver is very old, marked legacy driver by MongoDB and there are a lot of bug fixes in the newer versions.
Most importantly, we are running into some issues with bulk upsert in production and we're trying to see if we see those same issues with the latest Mongo java driver too.
Ran Hypertrace locally with the locally built image and things are working fine.
No functionality is changed, hence no docs needed.

feat: Upgrading docstore version to upgrade mongo java driver.

---

config-bootstrapper/build.gradle.kts

Upgrading docstore version to add support for postgres(hypertrace/document-store#9)

Upgrading docstore version to add support for postgres

---

helm/templates/config-bootstrapper-config.yaml
helm/values.yaml

Adds helm configs for enabling support for postgres (see more details at https://github.com/hypertrace/hypertrace/issues/124)
Generate the helm templates locally using the command - `helm template ./helm/` for various cases
- dataStoreType: "postgres"
- dataStoreType: "mongo"
This specific change may not require, but when we update in docker-compose for postgres, we will document it.

adding helm configs for postgres

---

.circleci/config.yml
config-bootstrapper/build.gradle.kts

Update framework version for vulnerability fixes, limit snyk to run on runtime code.
- [n/a] I have added tests that prove my fix is effective or that my feature works

chore: bump framework version and limit snyk to runtime

---

config-bootstrapper/build.gradle.kts

Updates the latest version of the service framework for integration test. (Ref issue which upgrades service framework: https://github.com/hypertrace/hypertrace/issues/137)

chore:updates service framework version

---

helm/templates/job.yaml

Instead of running two separate jobs for entity & attribute bootstrapping (proposed here https://github.com/hypertrace/config-bootstrapper/pull/33)
This pr adds a new job prefix called `attribute-entity`, for this job the program argument will be
```
args: [ "-c", "/etc/config-bootstrapper/application.conf", "-C", "/app/resources/configs/config-bootstrapper", "--upgrade" ]
```
which allows it to read both entity & attribute configs passed 
```
├── application.conf
├── attribute-service
│   ├── hypertrace
│   │   ├── hypertrace_api_attributes.conf
│   │   ├── hypertrace_api_trace_attributes.conf
│   │   ├── hypertrace_backend_attributes.conf
│   │   ├── hypertrace_backend_trace_attributes.conf
│   │   ├── hypertrace_interaction_attributes.conf
│   │   ├── hypertrace_service_attributes.conf …
```

Support for running attribute and entity bootstrap together 

---

.snyk
config-bootstrapper/build.gradle.kts

Updates doc-store version to include sqli fix - https://github.com/hypertrace/document-store/pull/30

chore: bump doc-store version to include sqli fix

---

config-bootstrapper/build.gradle.kts

Updates version of libs for netty to address,
- https://github.com/hypertrace/config-bootstrapper/runs/1868684886?check_suite_focus=true
- https://snyk.io/vuln/SNYK-JAVA-IONETTY-1070799

chore: bump version of netty proxy libs to fix the vulnerability

---

config-bootstrapper/build.gradle.kts

Updates doc-store version to include postgres impl of exists, not-exists, and NEQ filters
- hypertrace/document-store#35
- hypertrace/document-store#33

chore: bump doc-store version to include postgres impl of exits, not-exists and neq

---

helm/templates/bootstrap-configs.yaml
helm/templates/config-bootstrapper-config.yaml

Fix the post hook annotation for config map, this requires as while generating post-installation manifest files, it only copies the job, but it misses configmap - https://github.com/hypertrace/hypertrace/tree/main/kubernetes#create-deployment-manigests.

fix: update post hook annotation for config maps

---

.snyk
config-bootstrapper/build.gradle.kts
config-bootstrapper/src/integrationTest/resources/config-bootstrapper-test/application.conf
config-bootstrapper/src/integrationTest/resources/config-entity-service-test/application.conf

Uses a different mongo port than the standard 27017 port, to avoid affecting the local port forwarded mongo container

chore: separate mongo port for integration tests

---

config-bootstrapper/build.gradle.kts

Update attr version to bring in https://github.com/hypertrace/attribute-service/releases/tag/0.12.0 (specifically, the API additions from https://github.com/hypertrace/attribute-service/pull/93 )

chore: update attr client

---

.github/workflows/pr-test.yml

Forks don't have permissions to publish results back, so skip that step

ci: dont push ut results on forks

---

config-bootstrapper/build.gradle.kts
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace-core/hypertrace_core_event_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_span_attributes.conf

Removes several incorrectly defined attributes. 
- Service name is a hypertrace core attribute, so does not belong in the hypertrace definition file. Further, the hypertrace override of the definition incorrectly marks this attribute as internal.
- Domain ID and Domain name are not relevant to this project.
Updated image locally with change and verified in explorer UI
Closes https://github.com/hypertrace/hypertrace-ui/issues/1287

fix: remove incorrect attributes

---

config-bootstrapper/build.gradle.kts

- Upgrade the document store lib version and fixed the test to handle upgrade of hypertrace-service (ref : https://github.com/hypertrace/hypertrace-service/pull/123#issuecomment-1070371677)

chore: upgrade document-store lib version to latest

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_api_attributes.conf

Reverts hypertrace/config-bootstrapper#79

Revert "chore: API external from QS"

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_api_attributes.conf

Reverts hypertrace/config-bootstrapper#89

Revert "chore(attribute-service): added QS source for API.isExternal"

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_span_attributes.conf

The attributes aren't being used anywhere (and they don't have any sources, which could cause any UI queries to fail)

cleanup(hypertrace_event_attributes): invalid attributes
