hypertrace/config-bootstrapper

.circleci/config.yml
.snyk
config-bootstrapper/build.gradle.kts

Upgrade grpcutils for 0.1.3 to support binary headers

Upgrade grpcutils to 0.1.3 to support binary headers

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/entity-service/hypertrace-core/1_entityrelationshiptypes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/entity-service/hypertrace-core/1_entitytypes.conf

Remove DELETE actions, since they do blind bulk delete of all the types.

Remove DELETE actions from entity configs

---

helm/templates/job.yaml

check before monuting bootstrap-configs

check before monuting bootstrap-configs

---

README.md

- Created Readme and added one line description.

creates readme and adds one line description for service.

---

build.gradle.kts
config-bootstrapper/build.gradle.kts

@kotharironak if you don't mind looking at this one, it would be helpful as I noticed there's no log output but the exit code is zero

Updates to latest Docker plugin

---

.snyk

Resolve synk issues:
- Ignore netty related vulnerability reported by snyk  
- removes expired one related to grpc.

chore: fixing reported snyc vulnerability

---

.circleci/config.yml
build.gradle.kts

addresses https://github.com/hypertrace/hypertrace/issues/19 & https://github.com/hypertrace/hypertrace/issues/22

updates release workflow & gradle plugin

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace-core/1_event_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace-core/1_trace_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_api_trace_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_backend_trace_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_interaction_attributes.conf

Add new attributes to support https://github.com/hypertrace/hypertrace/issues/142
Manually verified

chore: add new space id attributes

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_api_trace_attributes.conf

Related to https://github.com/hypertrace/hypertrace-ingester/pull/138

Bootstrapper: Add api_exit_calls field

---

helm/templates/bootstrap-configs.yaml
helm/templates/config-bootstrapper-config.yaml

This reverts commit 0264dd216e3765fd2d1f3d1e86cfad7791877bc3.

Revert "fix: update post hook annotation for config maps (#40)"

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_backend_trace_attributes.conf

- Adding `backend_operation` attribute in attributes bootsrapper. 
NA

feat: adding backend_operation attribute in attributes bootstrapper

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_backend_trace_attributes.conf

Adding destination attribute in bootstrapper as we are working on adding Destination column in Backend Trace (call) view.
NA

chore: adds destination attribute in attributes bootstrapper

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace-core/1_event_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_service_attributes.conf

These attribute definitions allow these values to be used via the attribute reader either directly or composed into other attributes. Many more still need to be added.
Verified E2E locally

refactor: add service name, span times attr definitions

---

config-bootstrapper/build.gradle.kts

Update client versions and some other minor version bumps

chore: update clients

---

config-bootstrapper/build.gradle.kts
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_api_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_service_attributes.conf

Added EDS source for EDS attributes

chore: added eds source for eds attributes

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_log_event_attributes.conf

fix: Add rollback config

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace-core/hypertrace_core_event_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace-core/hypertrace_core_trace_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_api_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_api_trace_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_backend_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_backend_trace_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_interaction_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_log_event_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_service_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_span_attributes.conf

As discussed here https://github.com/hypertrace/config-bootstrapper/pull/54#discussion_r615881328

chore(attribute-service): rename attributes

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_log_event_attributes.conf

Add summary col
hypertrace/hypertrace#224

feat: Add summary col

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_span_attributes.conf

Ref issue : https://github.com/hypertrace/hypertrace-ui/issues/1157

Addition of span count attribute

---

config-bootstrapper/build.gradle.kts

fix: update log4j

---

.snyk
config-bootstrapper/build.gradle.kts
helm/templates/job.yaml
helm/values.yaml

Added security context to init containers to allow outgoing traffic when using Istio CNI.
https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers

Add security context to init containers

---

.snyk
config-bootstrapper/build.gradle.kts
config-bootstrapper/src/main/java/org/hypertrace/core/bootstrapper/commands/AttributeCommand.java

Adding `scope_string` support in `DELETE` command

DELETE: scope_string support

---

config-bootstrapper/src/main/resources/configs/config-bootstrapper/entity-service/hypertrace/1_entitytypes.conf

Reverts hypertrace/config-bootstrapper#84

Revert "chore | adding backend api identifying attributes"

---

build.gradle.kts
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace-core/hypertrace_core_event_attributes.conf
config-bootstrapper/src/main/resources/configs/config-bootstrapper/attribute-service/hypertrace/hypertrace_api_trace_attributes.conf

Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

Renaming the field Tags to Attributes

---

helm/templates/job.yaml

Changed restart policy of job from `OnFailure` to `Never`
deployed and tested helm chart locally.

fix: job restartPolicy to Never

---

helm/templates/job.yaml
helm/values.yaml

Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

Allow image version overrides with tag

---

.github/workflows/pr-build.yml
helm/templates/job.yaml
helm/values.yaml

Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

Inject Pod and Container Security Context
